language: cpp
sudo: required
dist: trusty
compiler:
- gcc
os:
- linux
branches:
  only:
  - master

addons:
  apt:
    config:
      retries: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - wget
      - bzip2
      - binutils
      # - texinfo

env:
  global:
  - LANG="en_US.UTF-8"   
  - JOBCOUNT=2
  - NAME_BINUTILS="binutils-2.31.1"
  - NAME_GCC="gcc-8.2.0"
  - NAME_LIBC="avr-libc-2.0.0"
  - OPTS_BINUTILS="--target=avr --disable-nls"
  - OPTS_GCC="--target=avr --enable-languages=c,c++ --disable-nls --disable-libssp --disable-libada --with-dwarf2 --disable-shared --enable-static"
  - OPTS_LIBC=""
  - PREFIX_LINUX=/home/travis/build/inares/avr-gcc/linux
  - PREFIX_LIBC=/home/travis/build/inares/avr-gcc/libc
  # - LANG="fr_FR.UTF-8"   

before_install:
- pwd
- export CC="gcc-8"
- export CXX="g++-8"
- export PATH="$PATH":"$PREFIX_LINUX"/bin
- wget http://ftp.gnu.org/gnu/binutils/${NAME_BINUTILS}.tar.xz
- wget http://mirror.rit.edu/gnu/gcc/${NAME_GCC}/${NAME_GCC}.tar.xz
- wget http://download.savannah.gnu.org/releases/avr-libc/${NAME_LIBC}.tar.bz2

script:
- sh build_binutils.sh
- sh build_gcc.sh
- sh build_avr-libc.sh
