language: cpp
sudo: required
dist: trusty
compiler:
- gcc
os:
- linux
branches:
  only:
  - master

addons:
  apt:
    config:
      retries: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      # - gcc-8
      # - g++-8
      - wget
      - bzip2
      # - binutils
      # - locate
      # - texinfo

env:
  global:
  # - LANG="fr_FR.UTF-8"   
  - LANG="en_US.UTF-8"   
  - JOBCOUNT=2
  - VER_BINUTILS="binutils-2.31.1"
  - VER_GCC="gcc-8.2.0"
  - VER_LIBC="avr-libc-2.0.0"
  - PREFIX_LINUX=/home/travis/build/inares/avr-gcc/linux
  - PREFIX_LIBC=/home/travis/build/inares/avr-gcc/libc

before_install:
- pwd
- df -h
# - gcc-8 --version
# - g++-8 --version
# - export CC="gcc-8"
# - export CXX="g++-8"
- unset CC CXX
- export PATH="$PATH":"$PREFIX_LINUX"/bin
- wget http://ftp.gnu.org/gnu/binutils/${NAME_BINUTILS}.tar.xz
- wget http://mirror.rit.edu/gnu/gcc/${NAME_GCC}/${NAME_GCC}.tar.xz
- wget http://download.savannah.gnu.org/releases/avr-libc/${NAME_LIBC}.tar.bz2

script:
- sh build_binutils.sh
- ll $PREFIX_LINUX
- travis_wait 45 sh build_gcc.sh
- ll $PREFIX_LINUX
- sh build_avr-libc.sh
- ll $PREFIX_LIBC

after_script:
- df -h