language: cpp
sudo: required
dist: trusty
compiler: gcc
os: linux
branches:
  only: master

#addons:
#  apt:
#    config:
#    retries: true
#    sources:
#      - ubuntu-toolchain-r-test
#    packages:
#      - gcc-8
#      - g++-8
#      - wget

cache:
  directories:
    - /home/travis/avr-gcc/
    - /home/travis/output/

git:
  depth: 1

env:
  global:
  # - LANG="fr_FR.UTF-8"
  - LANG="en_US.UTF-8"   
  - JOBCOUNT=2
  - VER_BINUTILS="2.31.1"
  - VER_GCC="8.2.0"
  - VER_LIBC="2.0.0"
  - PREFIX=/home/travis/avr-gcc
  - OUTPUT=/home/travis/output

before_install:
  - echo $TRAVIS_BUILD_DIR && echo $HOME && pwd
  - df -h
 # - export CC="gcc-8" CXX="g++-8"
  - unset CC CXX
  - export BINUTILS="binutils-${VER_BINUTILS}" GCC="gcc-${VER_GCC}" AVR_LIBC="avr-libc-${VER_LIBC}"
  - export PATH="$PATH":$PREFIX/bin RELEASE=$OUTPUT/avr-${GCC}.tar.bz2
  - git config --local user.name "INARES"
  - git config --local user.email "dev@inares.org"
  - git tag avr-${GCC}
  - mkdir -p $OUTPUT

script:
  - time sh build_binutils.sh
  - travis_wait 60 time sh build_gcc.sh
  - time sh build_avr-libc.sh
  - cd test
  - make && ls -alh
  - cd ..

before_deploy:
  - if [ ! -f "$RELEASE" ]; then echo "\n*** Creating archive file with avr-${GCC} ***" && cd $PREFIX/.. && tar -cjf $RELEASE avr-gcc && ls -lh $RELEASE ; fi

# https://docs.travis-ci.com/user/deployment/releases/
deploy:
  provider: releases
  api_key:
    secure: lLWtrqrv7o6gb9i0H+z4a8iOX28qf1VIu+Ld2/yzkk6cvneQrGrmVTald8mMbyIi7WkrD/uqHHf/1JIJdw5hrXanwdheFzcLXfJfzy0Ysk7K8VjYioM6YES7ipLKFroEuZp0VyUKoA0xmvWNk5efNlNelBUremlfg3Y+/+mnvQj7klzZGOkNi7gXsoE7Sm9tK1SX6MnZyD/7IueFSK/Ku74kfn7t4WtDQspsGKF21O6zw069EOeT9/BIHNYbRYDTGcfGkctvvil+LsHZTHXgKqGgVT3wR4RkCZ/UkRAHCNuIFRDJZDu2kuGUrz4+LdY8SkPcaycvbv/v0zbwsMARpTaLoqJJbZzC/VXEMzTwGzl+u0G5JVnJoS8q0606OgM0zlio8xVIdk/+KrVVXlSUWNl6U48fLADZlXgT7eKwKosemUdGG16HuZFOBw06BECg3aMZRFh+l7PJpopb040LTCeX7L3iAHRbKKlJHH8Wrq/2R3HxEPfexXjsO4otjMMqPXXfx7LNZQDBDpwQsqmRG/TDw603gJcQ2IHjaq0H9l+7JGNqfpExnzyIbOwiVn6YHU/3DpFSrIFsuCG8O0BTfp7b9vhkFwXHMTldhsoUcOfIy2hNSsfDdy4xPUkBeQ+/uGyUrFsAUiBXMayOfzzAhJveCXXvcV7TMTnHFcy3XNg=
  file: $RELEASE
  skip_cleanup: true
  overwrite: true

after_script:
  - ls -alh $PREFIX/bin
  - ls -alh $PREFIX/include
  - ls -alh $PREFIX/include/avr
  - ls -alh $OUTPUT
  - cd $OUTPUT && du -h --max-depth=1
  - cd $PREFIX && du -h --max-depth=1
